apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend-user
  template:
    metadata:
      labels:
        app: k8s-backend-user
    spec:
      containers:
      - name: k8s-backend-user
        image: goozip2/k8s-backend-user:0.0.8
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /etc/config
            name: backend-user-config-volume
            readOnly: true
          - mountPath: /etc/secret
            name: backend-user-secret-volume
            readOnly: true

      volumes:
        - name: backend-user-config-volume
          configMap:
            name: backend-user-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: backend-user-secret-volume
          secret:
            secretName: backend-user-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml